services:
  - type: web
    name: ptmsi-laravel
    env: php
    buildCommand: ""
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    plan: free
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:GGLlA3DUJ6nYEmmxY0b+7Nugnnzz2OQ5YkprTwiwx2k=
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://ptmsi.onrender.com
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_DEPRECATIONS_CHANNEL
        value: null
      - key: LOG_LEVEL
        value: debug

      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: "3307"
      - key: DB_DATABASE
        value: tcms_db
      - key: DB_USERNAME
        value: roshnivenga
      - key: DB_PASSWORD
        value: phpdotcom12345

      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: "120"
      - key: SESSION_DOMAIN
        value: null
      - key: SESSION_SECURE_COOKIE
        value: "false"

      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: sandbox.smtp.mailtrap.io
      - key: MAIL_PORT
        value: "2525"
      - key: MAIL_USERNAME
        value: b5cbd9c18184b7
      - key: MAIL_PASSWORD
        value: 23a764dd9def4e
      - key: MAIL_FROM_ADDRESS
        value: hello@example.com
      - key: MAIL_FROM_NAME
        value: Laravel

      - key: STRIPE_KEY
        value: pk_test_51RU7lPPLi0nHEyMSPhragDFw3DRMHKhLKvi57FKzleG9njmjYT5c17et213AQZ0EgFoIWFcduMOwEszjFoHagUyB001gFasARd
      - key: STRIPE_SECRET 
        sync: false

